spring:
  datasource:
#    db1:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dg?useSSL=false
    username: allsale_prod
    password: allsale@12345
#db2:
        ##      driver-class-name: com.mysql.cj.jdbc.Driver
        ##      jdbc-url: jdbc:mysql://39.108.92.8:3306/plan?useSSL=false
      ##      username: root
      ##      password: 521xwl54zql@MYSQL
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
