spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.12.142.19:3306/lawliet?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    # 使用明文密码
#    password: mysql@BD1
    # 使用密文密码
    password: K+UXEXyhl8aSZ6VjSmw6mJiTe+VRE1S9/HUsn7g/8s9hUZfIyVBbSe33Puyma2nUlF2Ar03NFGbuPTnaQ5OlpQ==
    druid:
      # 初始化时建立的连接个数
      initial-size: 3
      # 连接池最小连接数
      min-idle: 3
      # 连接池最大连接数
      max-active: 20
      # 获取连接时的最大等待时间，单位毫秒
      max-wait: 60000
      # 是否开启连接自动检测
      test-while-idle: true
      # 当开启连接自动检测时，这个值才有意义，如果该连接的空闲时间大于此值，就会执行validation-query去验证连接是否有效
      time-between-connect-error-millis: 60000
      # 检测当前连接的最后活动时间与当前时间的差值是否大于此值，大于则关闭该连接
      min-evictable-idle-time-millis: 30000
      # 定义用于检测的sql，MySQL使用 select 'x'，oracle使用 select 1 from dual
      validation-query: select 'x'
      # 申请连接时是否执行检测，默认false，这个非常影响性能
      test-on-borrow: false
      # 归还连接时是否执行检测，默认false，这个非常影响性能
      test-on-return: false
      # 是否缓存preparedStatement，建议开启
      pool-prepared-statements: true
      # 每个连接最大缓存的preparedStatement个数，如果设置为大于0的值，pool-prepared-statements特性会自动变为true
      max-pool-prepared-statement-per-connection-size: 20
      # 是否合并多个DruidDataSource的数据
      use-global-data-source-stat: false
      # 配置扩展插件，stat--监控，wall--SQL防注入，slf4j--日志
      filters: stat,wall,slf4j
      # connect-properties可以配置很多属性，如打开mergeSql功能、慢SQL记录等
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI3/IJ6xRfA3FZOtD+kngV9+NdhUhhFx2VGhUqQFeJ5zwZHGqZLFNQOHMeFVUOu26t03A0uBWyF/tbfJSShgM+kCAwEAAQ==
      # 定时输出统计信息到日志中
      time-between-log-stats-millis: 300000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      # 配置监控可视化界面
      stat-view-servlet:
        # 默认关闭，如需开启，建议同时开启密码和白名单，以保安全
        enabled: true
        url-pattern: '/druid/*'
        # IP白名单，不配置默认所有人都可以访问
        allow: 127.0.0.1,192.168.100.50
        # IP黑名单，如果和白名单重复，黑名单优先级高
        deny: 192.168.100.49,192.168.100.48
        # 禁止页面上的 reset all功能，无特殊需求的话，最好false
        reset-enable: false
        # 登录名
        login-username: druid-admin
        # 密码
        login-password: druid-admin
      filter:
        config:
          enabled: true
